frameworkVersion: ^2.16.1
service: star-wars-graphql
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
  apiKeys:
    - name: lambdaApolloKey
      value: ${env:APOLLO_LAMBDA_KEY}
functions:
  graphql:
    handler: src/handler.main
    events:
      - http:
          path: graphql
          method: post
          cors: true
          private: true
      - http:
          path: graphql
          method: get
          cors: true
          private: true
plugins:
  - serverless-webpack
  - serverless-offline-dotenv
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  webpack:
    includeModules: true
